version: 2

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Vet examines Go source code
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Advanced Go linter
    - unused         # Check for unused constants, variables, functions
    - gocritic       # Opinionated Go linter
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Find unused function parameters
    - gosec          # Security-focused linter
    - bodyclose      # Check for HTTP response body closure
    - errname        # Check error naming conventions
    - errorlint      # Find code that will cause problems with error wrapping
    - goconst        # Find repeated strings that could be constants
    - predeclared    # Find code that shadows predeclared identifiers
    - whitespace     # Check for unnecessary whitespace
    - revive         # Fast, configurable, extensible linter
  settings:
    staticcheck:
      checks: ["all", "-ST1017", "-ST1003"]  # Enable all checks except Yoda
    revive:
      disable:
        - var-naming  # Disable variable naming rule
      rules:
        - name: var-naming
          disabled: true

formatters:
  enable:
    - goimports       # Format code and manage imports
    - gofmt           # Strict code formatter


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst

run:
  timeout: 5m
  tests: true
  
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
